version: '3'

services: 
    spark-dev-env:
        build: ./dev
        stdin_open: true
        tty: true
        ports:
            - "8888:8888"
        volumes:
            - ./dev/docker-volume:/home/jovyan
        environment:
            - PYSPARK_SUBMIT_ARGS=--packages=org.apache.hadoop:hadoop-aws:2.7.3 pyspark-shell