version: '3'

services: 
    spark-dev-env:
        build: ./spark-dev-env
        stdin_open: true
        tty: true
        ports:
            - "8888:8888"
        volumes:
            - ./spark-dev-env/docker-img-volume:/home/jovyan
        environment:
            - PYSPARK_SUBMIT_ARGS=--packages=org.apache.hadoop:hadoop-aws:2.7.3 pyspark-shell